//Log in
export const LOGIN_SUCCESS_ACTION = 'LOGIN_SUCCESS_ACTION';
export const LOGIN_FAILURE_ACTION = 'LOGIN_FAILURE_ACTION';
export const LOGOUT_NOW_ACTION = 'LOGOUT_NOW_ACTION';

//Register
export const REGISTER_SUCCESS_ACTION = 'REGISTER_SUCCESS_ACTION';
export const REGISTER_FAILURE_ACTION = 'REGISTER_FAILURE_ACTION';

//Candidate Profile
export const PROFILE_SUCCESS_ACTION = 'PROFILE_SUCCESS_ACTION';
export const PROFILE_FAILURE_ACTION = 'PROFILE_FAILURE_ACTION';